#!/usr/bin/env python3
"""
Repo-to-Agentic Transformer
============================

Scans any repository and generates AI-agent-ready scaffolding files:
  - AGENTS.md       (GitHub Copilot / OpenAI)
  - CLAUDE.md       (Claude Code / Anthropic)
  - system_prompt.md (Universal — any LLM)
  - agent-context.json (Machine-readable context map)
  - MCP config       (mcp.json)
  - Tool templates   (per detected language)

Usage:
    python run_transformer.py --target /path/to/repo
    python run_transformer.py --target /path/to/repo --only agents
    python run_transformer.py --target /path/to/repo --dry-run

Generated by legacy-to-agentic-ready v1.0.0
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
TOOLKIT_ROOT = SCRIPT_DIR.parent
TEMPLATES_DIR = TOOLKIT_ROOT / "templates"

GENERATION_HEADER = "<!-- Generated by legacy-to-agentic-ready | Do not edit manually -->"
GENERATION_HEADER_JSON = '"_generated_by": "legacy-to-agentic-ready"'

LANGUAGE_EXTENSIONS: dict[str, list[str]] = {
    "Python": [".py"],
    "TypeScript": [".ts", ".tsx"],
    "JavaScript": [".js", ".jsx", ".mjs", ".cjs"],
    "Java": [".java"],
    "Go": [".go"],
    "Rust": [".rs"],
    "C#": [".cs"],
    "Ruby": [".rb"],
    "C++": [".cpp", ".cc", ".cxx", ".hpp", ".h"],
    "C": [".c"],
    "PHP": [".php"],
    "Swift": [".swift"],
    "Kotlin": [".kt", ".kts"],
}

CONFIG_FILES: dict[str, dict[str, str]] = {
    "package.json": {"language": "JavaScript/TypeScript", "build": "npm"},
    "tsconfig.json": {"language": "TypeScript", "build": "npm"},
    "pyproject.toml": {"language": "Python", "build": "pip"},
    "requirements.txt": {"language": "Python", "build": "pip"},
    "setup.py": {"language": "Python", "build": "pip"},
    "Pipfile": {"language": "Python", "build": "pipenv"},
    "go.mod": {"language": "Go", "build": "go"},
    "Cargo.toml": {"language": "Rust", "build": "cargo"},
    "pom.xml": {"language": "Java", "build": "maven"},
    "build.gradle": {"language": "Java", "build": "gradle"},
    "build.gradle.kts": {"language": "Kotlin", "build": "gradle"},
    "Gemfile": {"language": "Ruby", "build": "bundler"},
    "Makefile": {"language": None, "build": "make"},
    "CMakeLists.txt": {"language": "C/C++", "build": "cmake"},
}

FRAMEWORK_INDICATORS: dict[str, list[str]] = {
    "React": ["react", "react-dom"],
    "Next.js": ["next"],
    "Vue": ["vue"],
    "Angular": ["@angular/core"],
    "Express": ["express"],
    "NestJS": ["@nestjs/core"],
    "Django": ["django"],
    "Flask": ["flask"],
    "FastAPI": ["fastapi"],
    "Spring Boot": ["spring-boot-starter"],
    "Gin": ["github.com/gin-gonic/gin"],
    "Echo": ["github.com/labstack/echo"],
    "Rails": ["rails"],
    "ASP.NET": ["Microsoft.AspNetCore"],
    "Actix": ["actix-web"],
}

TEST_DIRECTORIES = ["test", "tests", "spec", "__tests__", "test_", "testing"]
TEST_FRAMEWORKS: dict[str, str] = {
    "pytest": "pytest",
    "unittest": "unittest",
    "jest": "jest",
    "mocha": "mocha",
    "vitest": "vitest",
    "junit": "junit",
    "go test": "go test",
    "rspec": "rspec",
    "minitest": "minitest",
    "xunit": "xunit",
    "nunit": "nunit",
}

IGNORE_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", "env",
    ".tox", ".mypy_cache", ".pytest_cache", "dist", "build", "target",
    ".next", ".nuxt", "out", "coverage", ".idea", ".vscode",
    ".gradle", ".mvn", "bin", "obj",
}

# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------


class RepoAnalyzer:
    """Analyzes a repository and extracts metadata for agent scaffolding."""

    def __init__(self, target: Path):
        self.target = target.resolve()
        self.name = self.target.name
        self.files: list[Path] = []
        self.languages: dict[str, int] = {}
        self.frameworks: list[str] = []
        self.build_system: str = "unknown"
        self.entry_points: list[str] = []
        self.test_framework: str = "unknown"
        self.test_directory: str = ""
        self.source_dirs: list[str] = []
        self.key_files: dict[str, str] = {}
        self.commands: dict[str, str] = {}
        self.description: str = ""
        self.conventions: dict[str, str] = {}
        self.env_vars: list[str] = []
        self.ci_platform: str = ""
        self.ci_config: str = ""

    def analyze(self) -> dict[str, Any]:
        """Run full repository analysis and return structured metadata."""
        print(f"🔍 Analyzing repository: {self.target}")

        self._scan_files()
        self._detect_languages()
        self._detect_config_and_build()
        self._detect_frameworks()
        self._detect_entry_points()
        self._detect_tests()
        self._detect_source_dirs()
        self._detect_key_files()
        self._detect_conventions()
        self._detect_ci()
        self._detect_env_vars()
        self._read_description()
        self._infer_commands()

        return self._to_dict()

    def _scan_files(self) -> None:
        """Walk the repository and collect all file paths."""
        for root, dirs, files in os.walk(self.target):
            # Prune ignored directories
            dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
            for f in files:
                full = Path(root) / f
                self.files.append(full)

        print(f"  📁 Found {len(self.files)} files")

    def _detect_languages(self) -> None:
        """Count files per language based on extensions."""
        for f in self.files:
            ext = f.suffix.lower()
            for lang, exts in LANGUAGE_EXTENSIONS.items():
                if ext in exts:
                    self.languages[lang] = self.languages.get(lang, 0) + 1
                    break

        # Sort by count descending
        self.languages = dict(
            sorted(self.languages.items(), key=lambda x: x[1], reverse=True)
        )
        if self.languages:
            print(f"  🌐 Languages: {', '.join(self.languages.keys())}")

    def _detect_config_and_build(self) -> None:
        """Detect build system from config files."""
        for config_file, info in CONFIG_FILES.items():
            if (self.target / config_file).exists():
                if info["build"] != "make" or self.build_system == "unknown":
                    self.build_system = info["build"]
                break

        print(f"  🔧 Build system: {self.build_system}")

    def _detect_frameworks(self) -> None:
        """Detect frameworks from dependency files."""
        # Check package.json
        pkg_json = self.target / "package.json"
        if pkg_json.exists():
            try:
                pkg = json.loads(pkg_json.read_text(encoding="utf-8"))
                all_deps = {
                    **pkg.get("dependencies", {}),
                    **pkg.get("devDependencies", {}),
                }
                for framework, indicators in FRAMEWORK_INDICATORS.items():
                    if any(ind in all_deps for ind in indicators):
                        self.frameworks.append(framework)
            except (json.JSONDecodeError, OSError):
                pass

        # Check requirements.txt / pyproject.toml
        for req_file in ["requirements.txt", "pyproject.toml", "Pipfile"]:
            req_path = self.target / req_file
            if req_path.exists():
                try:
                    content = req_path.read_text(encoding="utf-8").lower()
                    for framework, indicators in FRAMEWORK_INDICATORS.items():
                        if any(ind.lower() in content for ind in indicators):
                            if framework not in self.frameworks:
                                self.frameworks.append(framework)
                except OSError:
                    pass

        # Check go.mod
        go_mod = self.target / "go.mod"
        if go_mod.exists():
            try:
                content = go_mod.read_text(encoding="utf-8")
                for framework, indicators in FRAMEWORK_INDICATORS.items():
                    if any(ind in content for ind in indicators):
                        if framework not in self.frameworks:
                            self.frameworks.append(framework)
            except OSError:
                pass

        # Check pom.xml / build.gradle
        for build_file in ["pom.xml", "build.gradle", "build.gradle.kts"]:
            build_path = self.target / build_file
            if build_path.exists():
                try:
                    content = build_path.read_text(encoding="utf-8")
                    for framework, indicators in FRAMEWORK_INDICATORS.items():
                        if any(ind in content for ind in indicators):
                            if framework not in self.frameworks:
                                self.frameworks.append(framework)
                except OSError:
                    pass

        if self.frameworks:
            print(f"  📦 Frameworks: {', '.join(self.frameworks)}")

    def _detect_entry_points(self) -> None:
        """Find common entry point files."""
        entry_patterns = [
            "main.*", "app.*", "index.*", "server.*", "manage.py",
            "cli.*", "cmd/**/main.*", "src/main.*", "src/index.*",
            "src/app.*",
        ]
        for f in self.files:
            rel = f.relative_to(self.target)
            name = f.stem.lower()
            if name in ("main", "app", "index", "server", "manage", "cli"):
                self.entry_points.append(str(rel))

        if self.entry_points:
            print(f"  🚀 Entry points: {', '.join(self.entry_points[:5])}")

    def _detect_tests(self) -> None:
        """Find test directories and test framework."""
        for d in TEST_DIRECTORIES:
            test_dir = self.target / d
            if test_dir.is_dir():
                self.test_directory = d
                break

        # Detect test framework
        if (self.target / "pytest.ini").exists() or (self.target / "conftest.py").exists():
            self.test_framework = "pytest"
        elif (self.target / "jest.config.js").exists() or (self.target / "jest.config.ts").exists():
            self.test_framework = "jest"
        elif (self.target / "vitest.config.ts").exists():
            self.test_framework = "vitest"
        elif (self.target / ".rspec").exists():
            self.test_framework = "rspec"
        else:
            # Check package.json for test framework
            pkg_json = self.target / "package.json"
            if pkg_json.exists():
                try:
                    pkg = json.loads(pkg_json.read_text(encoding="utf-8"))
                    dev_deps = pkg.get("devDependencies", {})
                    for fw_name in ["jest", "mocha", "vitest", "ava", "tap"]:
                        if fw_name in dev_deps:
                            self.test_framework = fw_name
                            break
                except (json.JSONDecodeError, OSError):
                    pass

            # Check pyproject.toml
            pyproject = self.target / "pyproject.toml"
            if pyproject.exists() and self.test_framework == "unknown":
                try:
                    content = pyproject.read_text(encoding="utf-8")
                    if "pytest" in content:
                        self.test_framework = "pytest"
                except OSError:
                    pass

        if self.test_directory:
            print(f"  🧪 Tests: {self.test_directory}/ ({self.test_framework})")

    def _detect_source_dirs(self) -> None:
        """Identify source directories."""
        common_src_dirs = ["src", "lib", "app", "pkg", "internal", "cmd", "api", "core"]
        for d in common_src_dirs:
            if (self.target / d).is_dir():
                self.source_dirs.append(d)

    def _detect_key_files(self) -> None:
        """Identify important files and describe them."""
        key_file_patterns = {
            "README.md": "Project documentation and overview",
            "package.json": "Node.js dependencies and scripts",
            "tsconfig.json": "TypeScript compiler configuration",
            "pyproject.toml": "Python project metadata and dependencies",
            "requirements.txt": "Python dependencies",
            "go.mod": "Go module dependencies",
            "Cargo.toml": "Rust crate metadata and dependencies",
            "pom.xml": "Maven project configuration",
            "build.gradle": "Gradle build configuration",
            "Makefile": "Build automation targets",
            "Dockerfile": "Container image definition",
            "docker-compose.yml": "Multi-container Docker configuration",
            "docker-compose.yaml": "Multi-container Docker configuration",
            ".env.example": "Environment variable template",
            ".env.sample": "Environment variable template",
        }

        for filename, desc in key_file_patterns.items():
            if (self.target / filename).exists():
                self.key_files[filename] = desc

        # Add entry points
        for ep in self.entry_points[:5]:
            if ep not in self.key_files:
                self.key_files[ep] = "Application entry point"

    def _detect_conventions(self) -> None:
        """Detect coding conventions."""
        # Naming convention (heuristic from file names)
        snake_count = sum(1 for f in self.files if "_" in f.stem and f.stem[0].islower())
        camel_count = sum(
            1 for f in self.files
            if re.search(r"[a-z][A-Z]", f.stem) and not f.stem.startswith("_")
        )
        pascal_count = sum(1 for f in self.files if f.stem[0:1].isupper() and f.suffix in (".java", ".cs", ".kt"))

        if pascal_count > camel_count and pascal_count > snake_count:
            self.conventions["naming"] = "PascalCase"
        elif camel_count > snake_count:
            self.conventions["naming"] = "camelCase"
        else:
            self.conventions["naming"] = "snake_case"

        # Project structure
        if any((self.target / d).is_dir() for d in ["packages", "apps", "libs", "modules"]):
            self.conventions["structure"] = "monorepo"
        elif len(self.source_dirs) > 2:
            self.conventions["structure"] = "multi-module"
        else:
            self.conventions["structure"] = "single-package"

    def _detect_ci(self) -> None:
        """Detect CI/CD platform."""
        ci_files = {
            ".github/workflows": "GitHub Actions",
            ".gitlab-ci.yml": "GitLab CI",
            "Jenkinsfile": "Jenkins",
            ".circleci/config.yml": "CircleCI",
            ".travis.yml": "Travis CI",
            "azure-pipelines.yml": "Azure Pipelines",
            "bitbucket-pipelines.yml": "Bitbucket Pipelines",
        }
        for path, platform in ci_files.items():
            full = self.target / path
            if full.exists():
                self.ci_platform = platform
                self.ci_config = path
                break

    def _detect_env_vars(self) -> None:
        """Detect environment variables from .env files."""
        for env_file in [".env.example", ".env.sample", ".env.template"]:
            env_path = self.target / env_file
            if env_path.exists():
                try:
                    content = env_path.read_text(encoding="utf-8")
                    for line in content.splitlines():
                        line = line.strip()
                        if line and not line.startswith("#") and "=" in line:
                            var_name = line.split("=", 1)[0].strip()
                            self.env_vars.append(var_name)
                except OSError:
                    pass
                break

    def _read_description(self) -> None:
        """Extract project description from README."""
        readme = self.target / "README.md"
        if readme.exists():
            try:
                content = readme.read_text(encoding="utf-8")
                lines = content.splitlines()
                # Skip the title, find first paragraph
                in_paragraph = False
                paragraph_lines = []
                for line in lines[1:]:
                    stripped = line.strip()
                    if not stripped and in_paragraph:
                        break
                    if stripped and not stripped.startswith("#") and not stripped.startswith("!") and not stripped.startswith("["):
                        in_paragraph = True
                        paragraph_lines.append(stripped)

                if paragraph_lines:
                    self.description = " ".join(paragraph_lines)[:500]
            except OSError:
                pass

        if not self.description:
            self.description = f"A {', '.join(list(self.languages.keys())[:2]) or 'software'} project"

    def _infer_commands(self) -> None:
        """Infer build/test/run commands from the build system."""
        cmd_map: dict[str, dict[str, str]] = {
            "npm": {
                "install": "npm install",
                "build": "npm run build",
                "test": "npm test",
                "lint": "npm run lint",
                "run": "npm start",
            },
            "pip": {
                "install": "pip install -r requirements.txt",
                "build": "python -m build",
                "test": "pytest",
                "lint": "ruff check .",
                "run": "python -m {{MODULE}}",
            },
            "pipenv": {
                "install": "pipenv install",
                "build": "python -m build",
                "test": "pipenv run pytest",
                "lint": "pipenv run ruff check .",
                "run": "pipenv run python -m {{MODULE}}",
            },
            "go": {
                "install": "go mod download",
                "build": "go build ./...",
                "test": "go test ./...",
                "lint": "golangci-lint run",
                "run": "go run .",
            },
            "cargo": {
                "install": "cargo fetch",
                "build": "cargo build",
                "test": "cargo test",
                "lint": "cargo clippy",
                "run": "cargo run",
            },
            "maven": {
                "install": "mvn install",
                "build": "mvn package",
                "test": "mvn test",
                "lint": "mvn checkstyle:check",
                "run": "mvn exec:java",
            },
            "gradle": {
                "install": "./gradlew dependencies",
                "build": "./gradlew build",
                "test": "./gradlew test",
                "lint": "./gradlew check",
                "run": "./gradlew run",
            },
            "bundler": {
                "install": "bundle install",
                "build": "bundle exec rake build",
                "test": "bundle exec rspec",
                "lint": "bundle exec rubocop",
                "run": "bundle exec rails server",
            },
            "make": {
                "install": "make install",
                "build": "make build",
                "test": "make test",
                "lint": "make lint",
                "run": "make run",
            },
        }

        self.commands = cmd_map.get(self.build_system, {
            "install": "<TODO: verify>",
            "build": "<TODO: verify>",
            "test": "<TODO: verify>",
            "lint": "<TODO: verify>",
            "run": "<TODO: verify>",
        })

        # Override test command if we detected a specific framework
        if self.test_framework == "pytest":
            self.commands["test"] = "pytest"
        elif self.test_framework == "jest":
            self.commands["test"] = "npx jest"
        elif self.test_framework == "vitest":
            self.commands["test"] = "npx vitest"

        # Check for scripts in package.json
        pkg_json = self.target / "package.json"
        if pkg_json.exists():
            try:
                pkg = json.loads(pkg_json.read_text(encoding="utf-8"))
                scripts = pkg.get("scripts", {})
                if "build" in scripts:
                    self.commands["build"] = "npm run build"
                if "test" in scripts:
                    self.commands["test"] = "npm test"
                if "lint" in scripts:
                    self.commands["lint"] = "npm run lint"
                if "start" in scripts:
                    self.commands["run"] = "npm start"
                if "dev" in scripts:
                    self.commands["run"] = "npm run dev"
            except (json.JSONDecodeError, OSError):
                pass

    def _to_dict(self) -> dict[str, Any]:
        """Convert analysis results to a dictionary."""
        return {
            "project_name": self.name,
            "description": self.description,
            "primary_languages": list(self.languages.keys()),
            "frameworks": self.frameworks,
            "build_system": self.build_system,
            "entry_points": self.entry_points,
            "test_framework": self.test_framework,
            "test_directory": self.test_directory,
            "source_directories": self.source_dirs,
            "key_files": self.key_files,
            "conventions": self.conventions,
            "commands": self.commands,
            "environment": {
                "required_env_vars": self.env_vars,
            },
            "ci_cd": {
                "platform": self.ci_platform,
                "config_file": self.ci_config,
            },
        }


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class AgenticGenerator:
    """Generates AI-agent-ready files from repository metadata."""

    def __init__(self, target: Path, metadata: dict[str, Any], dry_run: bool = False):
        self.target = target
        self.meta = metadata
        self.dry_run = dry_run
        self.generated: list[str] = []

    def generate_all(self) -> list[str]:
        """Generate all agent-ready files."""
        self.generate_context_json()
        self.generate_agents_md()
        self.generate_claude_md()
        self.generate_system_prompt()
        self.generate_mcp_json()
        self.generate_tool_templates()
        return self.generated

    def generate_only(self, category: str) -> list[str]:
        """Generate only a specific category of files."""
        category_map = {
            "agents": [self.generate_agents_md, self.generate_claude_md, self.generate_system_prompt],
            "context": [self.generate_context_json],
            "tools": [self.generate_tool_templates],
            "mcp": [self.generate_mcp_json],
        }

        generators = category_map.get(category, [])
        if not generators:
            print(f"❌ Unknown category: {category}")
            print(f"   Valid categories: {', '.join(category_map.keys())}")
            sys.exit(1)

        for gen in generators:
            gen()

        return self.generated

    def _write_file(self, rel_path: str, content: str) -> None:
        """Write a file to the target repo (or simulate in dry-run mode)."""
        full_path = self.target / rel_path
        if self.dry_run:
            print(f"  📝 [DRY RUN] Would create: {rel_path}")
        else:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            print(f"  ✅ Created: {rel_path}")
        self.generated.append(rel_path)

    def _dir_tree(self, max_depth: int = 3) -> str:
        """Generate a directory tree string."""
        lines = [f"{self.meta['project_name']}/"]
        entries = sorted(self.target.iterdir(), key=lambda p: (not p.is_dir(), p.name))

        for entry in entries:
            if entry.name in IGNORE_DIRS or entry.name.startswith("."):
                continue
            prefix = "├── " if entry != entries[-1] else "└── "
            if entry.is_dir():
                lines.append(f"{prefix}{entry.name}/")
                if max_depth > 1:
                    sub_entries = sorted(entry.iterdir(), key=lambda p: (not p.is_dir(), p.name))
                    for sub in sub_entries[:10]:
                        if sub.name in IGNORE_DIRS:
                            continue
                        sub_prefix = "│   ├── " if sub != sub_entries[-1] else "│   └── "
                        suffix = "/" if sub.is_dir() else ""
                        lines.append(f"{sub_prefix}{sub.name}{suffix}")
                    if len(sub_entries) > 10:
                        lines.append("│   └── ...")
            else:
                lines.append(f"{prefix}{entry.name}")

        return "\n".join(lines)

    def _fill_template(self, template_content: str) -> str:
        """Replace template placeholders with actual metadata values."""
        m = self.meta
        replacements = {
            "{{PROJECT_NAME}}": m["project_name"],
            "{{PROJECT_DESCRIPTION}}": m["description"],
            "{{PRIMARY_LANGUAGES}}": ", ".join(m["primary_languages"]) or "Unknown",
            "{{FRAMEWORKS}}": ", ".join(m["frameworks"]) or "None detected",
            "{{BUILD_SYSTEM}}": m["build_system"],
            "{{TEST_FRAMEWORK}}": m["test_framework"],
            "{{TEST_DIRECTORY}}": m["test_directory"] or "tests/",
            "{{DIRECTORY_TREE}}": self._dir_tree(),
            "{{INSTALL_COMMAND}}": m["commands"].get("install", "<TODO: verify>"),
            "{{BUILD_COMMAND}}": m["commands"].get("build", "<TODO: verify>"),
            "{{RUN_COMMAND}}": m["commands"].get("run", "<TODO: verify>"),
            "{{TEST_COMMAND}}": m["commands"].get("test", "<TODO: verify>"),
            "{{LINT_COMMAND}}": m["commands"].get("lint", "<TODO: verify>"),
            "{{FORMAT_COMMAND}}": m["commands"].get("format", "<TODO: verify>"),
            "{{NAMING_CONVENTION}}": m["conventions"].get("naming", "snake_case"),
            "{{PROJECT_STRUCTURE}}": m["conventions"].get("structure", "single-package"),
            "{{TIMESTAMP}}": datetime.now(timezone.utc).isoformat(),
        }

        result = template_content
        for placeholder, value in replacements.items():
            result = result.replace(placeholder, str(value))

        return result

    def generate_context_json(self) -> None:
        """Generate agent-context.json."""
        context = {
            "_generated_by": "legacy-to-agentic-ready",
            "_generated_at": datetime.now(timezone.utc).isoformat(),
            "_version": "1.0.0",
            **self.meta,
        }
        content = json.dumps(context, indent=2, ensure_ascii=False)
        self._write_file("agent-context.json", content)

    def generate_agents_md(self) -> None:
        """Generate AGENTS.md for GitHub Copilot / OpenAI."""
        m = self.meta
        lines = [
            GENERATION_HEADER,
            f"# AGENTS.md — {m['project_name']}",
            "",
            "## Project Overview",
            "",
            f"**{m['project_name']}** — {m['description']}",
            "",
            f"- **Primary Languages:** {', '.join(m['primary_languages']) or 'Unknown'}",
            f"- **Frameworks:** {', '.join(m['frameworks']) or 'None detected'}",
            f"- **Build System:** {m['build_system']}",
            "",
            "---",
            "",
            "## Repository Structure",
            "",
            "```",
            self._dir_tree(),
            "```",
            "",
            "## Key Files",
            "",
            "| File | Purpose |",
            "|------|---------|",
        ]

        for path, desc in m["key_files"].items():
            lines.append(f"| `{path}` | {desc} |")

        lines.extend([
            "",
            "---",
            "",
            "## Commands",
            "",
            "```bash",
            f"# Install dependencies",
            f"{m['commands'].get('install', '<TODO: verify>')}",
            "",
            f"# Build",
            f"{m['commands'].get('build', '<TODO: verify>')}",
            "",
            f"# Run",
            f"{m['commands'].get('run', '<TODO: verify>')}",
            "",
            f"# Test",
            f"{m['commands'].get('test', '<TODO: verify>')}",
            "",
            f"# Lint",
            f"{m['commands'].get('lint', '<TODO: verify>')}",
            "```",
            "",
            "---",
            "",
            "## Code Conventions",
            "",
            f"- **Naming:** {m['conventions'].get('naming', 'snake_case')}",
            f"- **Structure:** {m['conventions'].get('structure', 'single-package')}",
            "",
            "---",
            "",
            "## Testing",
            "",
            f"- **Framework:** {m['test_framework']}",
            f"- **Directory:** `{m['test_directory'] or 'tests/'}`",
            f"- **Run:** `{m['commands'].get('test', '<TODO: verify>')}`",
            "",
        ])

        self._write_file("AGENTS.md", "\n".join(lines))

    def generate_claude_md(self) -> None:
        """Generate CLAUDE.md for Claude Code / Anthropic."""
        m = self.meta
        lines = [
            GENERATION_HEADER,
            f"# CLAUDE.md — {m['project_name']}",
            "",
            "## Project Identity",
            "",
            f"This is **{m['project_name']}** — {m['description']}.",
            "",
            f"Built with **{', '.join(m['primary_languages']) or 'Unknown'}** "
            f"using **{', '.join(m['frameworks']) or 'no specific framework'}**.",
            "",
            "---",
            "",
            "## Critical Commands",
            "",
            "```bash",
            "# Install dependencies",
            m['commands'].get('install', '<TODO: verify>'),
            "",
            "# Build the project",
            m['commands'].get('build', '<TODO: verify>'),
            "",
            "# Run the project",
            m['commands'].get('run', '<TODO: verify>'),
            "",
            "# Run all tests",
            m['commands'].get('test', '<TODO: verify>'),
            "",
            "# Lint",
            m['commands'].get('lint', '<TODO: verify>'),
            "```",
            "",
            "---",
            "",
            "## Repository Map",
            "",
            "```",
            self._dir_tree(),
            "```",
            "",
            "### Key Files",
            "",
        ]

        for path, desc in m["key_files"].items():
            lines.append(f"- **`{path}`** — {desc}")

        lines.extend([
            "",
            "---",
            "",
            "## Rules — ALWAYS Follow",
            "",
            f"1. Always run `{m['commands'].get('test', 'tests')}` after making changes",
            f"2. Always run `{m['commands'].get('lint', 'linter')}` before committing",
            f"3. Use {m['conventions'].get('naming', 'snake_case')} for all new files and symbols",
            "4. Follow the existing import ordering convention",
            "5. Add tests for every new function or endpoint",
            "6. Keep functions small — max 50 lines per function",
            "",
            "## Rules — NEVER Do",
            "",
            "1. Never modify auto-generated files",
            "2. Never commit secrets, tokens, or credentials",
            "3. Never use wildcard imports unless the module is designed for it",
            "4. Never skip error handling",
            "5. Never reference paths that don't exist in the repository",
            "",
            "---",
            "",
            "## Testing",
            "",
            f"- **Framework:** {m['test_framework']}",
            f"- **Directory:** `{m['test_directory'] or 'tests/'}`",
            f"- **Run all:** `{m['commands'].get('test', '<TODO: verify>')}`",
            "",
        ])

        self._write_file("CLAUDE.md", "\n".join(lines))

    def generate_system_prompt(self) -> None:
        """Generate system_prompt.md (universal — any LLM)."""
        m = self.meta
        lines = [
            GENERATION_HEADER,
            f"# System Prompt — {m['project_name']}",
            "",
            f"You are an expert AI coding assistant working on **{m['project_name']}**.",
            "",
            "## Project Context",
            "",
            m["description"],
            "",
            f"- **Languages:** {', '.join(m['primary_languages']) or 'Unknown'}",
            f"- **Frameworks:** {', '.join(m['frameworks']) or 'None detected'}",
            f"- **Build System:** {m['build_system']}",
            f"- **Test Framework:** {m['test_framework']}",
            "",
            "## Repository Structure",
            "",
            "```",
            self._dir_tree(),
            "```",
            "",
            "## Key Files",
            "",
        ]

        for path, desc in m["key_files"].items():
            lines.append(f"- `{path}` — {desc}")

        lines.extend([
            "",
            "## Available Commands",
            "",
            "| Action  | Command |",
            "|---------|---------|",
            f"| Install | `{m['commands'].get('install', '<TODO: verify>')}` |",
            f"| Build   | `{m['commands'].get('build', '<TODO: verify>')}` |",
            f"| Run     | `{m['commands'].get('run', '<TODO: verify>')}` |",
            f"| Test    | `{m['commands'].get('test', '<TODO: verify>')}` |",
            f"| Lint    | `{m['commands'].get('lint', '<TODO: verify>')}` |",
            "",
            "## Code Conventions",
            "",
            f"- **Naming:** {m['conventions'].get('naming', 'snake_case')}",
            f"- **Structure:** {m['conventions'].get('structure', 'single-package')}",
            "",
            "## Mandatory Rules",
            "",
            "1. Only reference files and paths that exist in the repository",
            "2. Never modify auto-generated files",
            "3. Always write tests for new functionality",
            "4. Follow the existing code style and conventions",
            "5. Handle errors explicitly — never silently ignore them",
            "",
        ])

        self._write_file("system_prompt.md", "\n".join(lines))

    def generate_mcp_json(self) -> None:
        """Generate mcp.json with MCP server configuration."""
        config = {
            "_generated_by": "legacy-to-agentic-ready",
            "_generated_at": datetime.now(timezone.utc).isoformat(),
            "mcpServers": {
                "filesystem": {
                    "command": "npx",
                    "args": ["-y", "@modelcontextprotocol/server-filesystem", "."],
                },
                "git": {
                    "command": "uvx",
                    "args": ["mcp-server-git", "--repository", "."],
                },
            },
        }
        content = json.dumps(config, indent=2, ensure_ascii=False)
        self._write_file("mcp.json", content)

    def generate_tool_templates(self) -> None:
        """Generate tool template files for each detected language."""
        lang_to_template = {
            "Python": "tool.python.template.py",
            "TypeScript": "tool.typescript.template.ts",
            "JavaScript": "tool.typescript.template.ts",
            "Java": "tool.java.template.java",
            "Go": "tool.go.template.go",
        }

        lang_to_output = {
            "Python": "tools/example_tool.py",
            "TypeScript": "tools/example_tool.ts",
            "JavaScript": "tools/example_tool.ts",
            "Java": "tools/ExampleTool.java",
            "Go": "tools/example_tool.go",
        }

        generated_outputs = set()
        for lang in self.meta["primary_languages"]:
            template_file = lang_to_template.get(lang)
            output_file = lang_to_output.get(lang)
            if template_file and output_file and output_file not in generated_outputs:
                template_path = TEMPLATES_DIR / template_file
                if template_path.exists():
                    content = template_path.read_text(encoding="utf-8")
                    self._write_file(output_file, content)
                    generated_outputs.add(output_file)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Transform any repository into an AI-agent-ready codebase.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python run_transformer.py --target /path/to/repo
  python run_transformer.py --target /path/to/repo --only agents
  python run_transformer.py --target /path/to/repo --dry-run
  python run_transformer.py --target . --verbose
        """,
    )
    parser.add_argument(
        "--target", "-t",
        type=str,
        required=True,
        help="Path to the target repository to transform",
    )
    parser.add_argument(
        "--only",
        type=str,
        choices=["agents", "context", "tools", "mcp"],
        default=None,
        help="Only generate a specific category of files",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be generated without writing files",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose output",
    )

    args = parser.parse_args()
    target = Path(args.target).resolve()

    if not target.is_dir():
        print(f"❌ Target directory does not exist: {target}")
        sys.exit(1)

    print()
    print("╔══════════════════════════════════════════════╗")
    print("║   🤖 Repo-to-Agentic Transformer v1.0.0     ║")
    print("╚══════════════════════════════════════════════╝")
    print()

    # Phase 1: Analysis
    analyzer = RepoAnalyzer(target)
    metadata = analyzer.analyze()

    print()

    # Phase 2: Generation
    generator = AgenticGenerator(target, metadata, dry_run=args.dry_run)

    if args.only:
        generated = generator.generate_only(args.only)
    else:
        generated = generator.generate_all()

    # Summary
    print()
    print("─" * 46)
    mode = "[DRY RUN] " if args.dry_run else ""
    print(f"✅ {mode}Transformation Complete")
    print("─" * 46)
    print(f"  Project:    {metadata['project_name']}")
    print(f"  Languages:  {', '.join(metadata['primary_languages']) or 'Unknown'}")
    print(f"  Frameworks: {', '.join(metadata['frameworks']) or 'None detected'}")
    print(f"  Build:      {metadata['build_system']}")
    print()
    print("  Generated Files:")
    for f in generated:
        print(f"    ✓ {f}")
    print()
    print("  No existing files were modified.")
    print()


if __name__ == "__main__":
    main()
