#!/usr/bin/env python3
"""
Repo-to-Agentic Transformer

Transforms any repository into an AI-agent-ready codebase by detecting:
- Languages, frameworks, and build systems
- Entry points and test frameworks
- Environment configuration
- Code conventions

Then generates:
- agent-context.json (machine-readable metadata)
- AGENTS.md (GitHub Copilot / OpenAI instructions)
- CLAUDE.md (Claude Code instructions)
- system_prompt.md (Universal LLM system prompt)
- mcp.json (MCP server configuration)
- Tool templates (language-specific)
- memory/schema.md (domain-specific memory schema)

Usage:
  python run_transformer.py --target /path/to/repo
  python run_transformer.py --target /path/to/repo --only agents
  python run_transformer.py --target /path/to/repo --dry-run
  python run_transformer.py --target /path/to/repo --provider anthropic

Generated by AgentReady (agent-ready) v1.1.0
"""

from agent_ready.cli import main

if __name__ == "__main__":
    main()
